server:
  port: 8084

mybatis:
  config-location: classpath:META-INF/mybatis-config.xml

# 该文件为默认配置
sharding:
  jdbc:
    datasource:
      names: ds_master,ds_slave
      ds_master:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:43306/ds_0?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: root
        password: password
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        initial-size: 5
        validation-query: SELECT 1
        test-on-borrow: false
        test-while-idle: true
        time-between-eviction-runs-millis: 18800
        jdbc-interceptors: ConnectionState;
      ds_slave:
        type: com.alibaba.druid.pool.DruidDataSource
        driver-class-name: com.mysql.jdbc.Driver
        url: jdbc:mysql://localhost:43306/ds_0?useSSL=false&serverTimezone=UTC&useUnicode=true&characterEncoding=utf-8
        username: root
        password: password
        max-idle: 10
        max-wait: 10000
        min-idle: 5
        initial-size: 5
        validation-query: SELECT 1
        test-on-borrow: false
        test-while-idle: true
        time-between-eviction-runs-millis: 18800
        jdbc-interceptors: ConnectionState;

    config:
    # 读写+分表 不需要的配置。 只有读写需要
#      masterslave:
#        load-balance-algorithm-type: round_robin
#        name: dataSource
#        master-data-source-name: ds_master
#        slave-data-source-names: ds_slave

      sharding:
        tables:
          user:
            actual-data-nodes: ds_master.user_$->{0..3}
            table-strategy:
              inline:
                sharding-column: id
                algorithm-expression: user_$->{id.longValue() % 4}
            key-generator-column-name: id
        binding-tables: user
        default-data-source-name: ds_master
        master-slave-rules:
          ds_master:
            master-data-source-name: ds_master
            slave-data-source-names: ds_slave
        props:
          sql:
            show: true